//API
export const API_TOKEN = "access_token";
export const API_AUTO_GENERATE = "autoGenerated";

//Routes
export const ROUTE_ROOT = "/";
export const ROUTE_IDP_MANAGE = "/idp/manage";
export const ROUTE_IDP_CREATE = "/idp/create";
export const ROUTE_ABOUT_WHAT = "/about/what";
export const ROUTE_ABOUT_ORGANISATION = "/about/organisations";
export const ROUTE_ABOUT_FEDERATION = "/about/federations";
